//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionTecnologiaCampos
    {
        public long ConfiguracionTecnologiaCamposId { get; set; }
        public string NombreCampo { get; set; }
        public string TablaProcedencia { get; set; }
        public string DescripcionCampo { get; set; }
        public Nullable<int> FlagActivo { get; set; }
        public string RolAprueba { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> CorrelativoCampo { get; set; }
        public Nullable<int> FlagConfiguracion { get; set; }
    }
}
