//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoSolicitud
    {
        public int EquipoSolicitudId { get; set; }
        public Nullable<int> EquipoId { get; set; }
        public int EstadoSolicitud { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string NombreUsuarioCreacion { get; set; }
        public string Comentarios { get; set; }
        public byte[] ArchivoConstancia { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string NombreUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacionRechazo { get; set; }
        public string AprobadoRechazadoPor { get; set; }
        public string NombreUsuarioAprobadoRechazo { get; set; }
        public int TipoEquipoActual { get; set; }
        public int TipoEquipoSolicitado { get; set; }
        public Nullable<System.DateTime> FechaFinSoporte { get; set; }
        public string ComentariosDesestimacion { get; set; }
        public string ComentariosAprobacionRechazo { get; set; }
        public string NombreArchivo { get; set; }
        public string CorreoSolicitante { get; set; }
        public string CodigoAPT { get; set; }
        public string UsuarioAsignado { get; set; }
        public Nullable<bool> FlagSeguridad { get; set; }
        public Nullable<bool> FlagRegistroEquipo { get; set; }
        public Nullable<System.DateTime> FechaAprobacionRechazoCVT { get; set; }
        public string AprobadoRechazoCVT { get; set; }
        public string NombreEquipo { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
