//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardicoreEtiquetadoEquipos
    {
        public int EtiquetaEquipoId { get; set; }
        public Nullable<int> EquipoId { get; set; }
        public string NombreEquipo { get; set; }
        public string Etiqueta { get; set; }
        public Nullable<bool> EstadoEtiqueta { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string EquipoGuardicoreId { get; set; }
        public string EtiquetaGuardicoreId { get; set; }
        public Nullable<int> TipoEtiqueta { get; set; }
        public string Ip { get; set; }
    }
}
