//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoManagerRoles
    {
        public long ProductoManagerRolesId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public string ManagerMatricula { get; set; }
        public string ManagerNombre { get; set; }
        public string ManagerEmail { get; set; }
        public bool FlagActivo { get; set; }
        public Nullable<int> ProductoManagerId { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
