//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudRelacionFuncion
    {
        public int SolicitudRelacionFuncionId { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> TipoAsignacion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public string Tribu { get; set; }
        public string Chapter { get; set; }
        public string Funcion { get; set; }
        public string RolSeguridad { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public string Producto { get; set; }
        public string Rol { get; set; }
        public Nullable<int> RolId { get; set; }
    }
}
