//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudTecnologia
    {
        public long SolicitudTecnologiaId { get; set; }
        public Nullable<int> TipoSolicitud { get; set; }
        public Nullable<int> TecnologiaId { get; set; }
        public Nullable<int> EstadoSolicitud { get; set; }
        public string MotivoDesactiva { get; set; }
        public string UsuarioSolicitante { get; set; }
        public string NombreUsuarioSolicitante { get; set; }
        public string EmailSolicitante { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> MotivoDesactivaId { get; set; }
        public Nullable<int> ProductoId { get; set; }
    }
}
