//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudTecnologiaFlujo
    {
        public long SolicitudTecnologiaFlujoId { get; set; }
        public Nullable<int> SolicitudTecnologiaId { get; set; }
        public Nullable<int> TipoFlujo { get; set; }
        public Nullable<int> EstadoFlujo { get; set; }
        public string AprobadoPor { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string RechazadoPor { get; set; }
        public Nullable<System.DateTime> FechaRechazo { get; set; }
        public string MotivoRechazo { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ResponsableMatricula { get; set; }
        public string ResponsableBuzon { get; set; }
    }
}
