//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudRelacionFuncionDetalle
    {
        public int SolicitudRelacionFuncionDetalleId { get; set; }
        public Nullable<int> SolicitudRelacionFuncionId { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> TipoAsignacion { get; set; }
        public string Tribu { get; set; }
        public string Chapter { get; set; }
        public string Funcion { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public string RolCVT { get; set; }
        public string RolSeguridad { get; set; }
        public Nullable<int> RolId { get; set; }
        public string Descripcion { get; set; }
        public string GrupoRed { get; set; }
        public string RevisadoPor { get; set; }
        public string EliminadoPor { get; set; }
        public string Comentario { get; set; }
        public string DocumentoAdjunto { get; set; }
        public string NombreResponsable { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<bool> FlagActivo { get; set; }
        public Nullable<bool> FlagEliminado { get; set; }
    }
}
