//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolRolFuncionHistorial
    {
        public long IdSolRolFuncionHistorial { get; set; }
        public Nullable<long> IdSolRolFuncionCabecera { get; set; }
        public string Comentario { get; set; }
        public string ObservacionSeguridad { get; set; }
        public string ObservacionOwner { get; set; }
        public Nullable<int> EstadoSolicitudHistorial { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public string RevisadoPor { get; set; }
    }
}
